"""Initial schema

Revision ID: 9c6605d06187
Revises: 
Create Date: 2026-06-21 18:40:24.882450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6605d06187'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('count', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query')
    )
    op.create_index('idx_queries_count_desc', 'queries', [sa.literal_column('count DESC')], unique=False)
    op.create_index('idx_queries_query_btree', 'queries', [sa.literal_column('query text_pattern_ops')], unique=False)
    op.create_index('idx_queries_query_trgm', 'queries', [sa.literal_column('query gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.create_table('recent_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recent_query', 'recent_searches', ['query'], unique=False)
    op.create_index('idx_recent_searched_at', 'recent_searches', ['searched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recent_searched_at', table_name='recent_searches')
    op.drop_index('idx_recent_query', table_name='recent_searches')
    op.drop_table('recent_searches')
    op.drop_index('idx_queries_query_trgm', table_name='queries', postgresql_using='gin')
    op.drop_index('idx_queries_query_btree', table_name='queries')
    op.drop_index('idx_queries_count_desc', table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ###
    op.execute('DROP EXTENSION IF EXISTS pg_trgm;')
